### ISSUE TITLE
Google crackdown on Diffusion WebUI

### ISSUE THREAD

**Issue by acheong08** [acheong08/Diffusion-ColabUI#10]
Google has been cracking down on web services being hosted via Colab. Please be aware that your account may become locked given extensive use.

**Comment by GrennKren** [comment]
Looks like it was actually false positive
<img src="https://user-images.githubusercontent.com/34759917/197593450-aa03e312-fdd2-4c50-944c-a4a4f5c562d8.jpg" width="500px">

**Comment by acheong08** [comment]
That's good to hear. I suppose this is resolved for now
