### ISSUE TITLE
error

### ISSUE THREAD

**Issue by PutraCoud** [acheong08/Diffusion-ColabUI#101]
fatal: destination path 'stable-diffusion-webui' already exists and is not an empty directory.
/content/stable-diffusion-webui
Already up to date.
Already on 'v2'
Your branch is up to date with 'origin/v2'.
/content
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-04432ca3eb97> in <module>
    124   get_ipython().system('COMMANDLINE_ARGS="{other_args} {vae_args} {vram} --gradio-auth {gradio_username}:{gradio_password} {output_path}" REQS_FILE="requirements.txt" python launch.py')
    125 
--> 126 install_deps()
    127 run_webui()
    128 #@markdown # Common issues

<ipython-input-1-04432ca3eb97> in install_deps()
     89 
     90   # Get models
---> 91   for model in customModels:
     92     custom_model(model[0], model[1], model[2])
     93   if use_hypernetworks:

NameError: name 'customModels' is not defined

**Comment by acheong08** [comment]
Did you forget to define the models?

**Comment by acheong08** [comment]
It's in the cell above

**Comment by PutraCoud** [comment]
> 

i did, that happen after restarting webui

**Comment by acheong08** [comment]
Restarting the UI means you have to set the models again. Python variables get cleared by colab

**Comment by PutraCoud** [comment]
> 

oops thank you

just one thing, it happen everytime i use webui, it's always showing *C and then just turned off, what was that ?

**Comment by acheong08** [comment]
Ran out of RAM.

**Comment by acheong08** [comment]
It's a limit by Google. I can't fix it

**Comment by PutraCoud** [comment]
> 

Thank you for answering 🙏
