### ISSUE TITLE
execution stops and ^C at the final line

### ISSUE THREAD

**Issue by JustNerro** [acheong08/Diffusion-ColabUI#11]
Cannot use the Colab at all, execution stops on its own and gives a "^C" at the last line after selecting a model in the webui and loading the model weight.

Noticing a usage spike on RAM, I then tried using -lowvram.
The RAM usage spike is no more but the ^C thing problem still persists.

Was working without problem yesterday.

**Comment by acheong08** [comment]
It might be that Google is terminating the process. They seem to have been cracking down on image generation due to the potential of illegal use as well as the hosting of the gradio services. I am not encountering this error though.

**Comment by acheong08** [comment]
Cannot replicate
