### ISSUE TITLE
Problems with "conection errored out"

### ISSUE THREAD

**Issue by wikibamxd** [acheong08/Diffusion-ColabUI#117]
https://i.imgur.com/pDo0GRu.png
i generated an image with a model and then i wanted to switch to another one and it just crashed, the execution stopped.
and even just going to the image browser.
theres not a single time that i run the colab and the connection goes errors out

**Comment by acheong08** [comment]
It should be. I updated a few things and swapped to using a well maintained fork https://github.com/vladmandic/automatic
