### ISSUE TITLE
Excuse me, would it be possible to update some useful plugins? Thank you very much.

### ISSUE THREAD

**Issue by Molli2967832506** [acheong08/Diffusion-ColabUI#118]
It's always a hassle for me to download these plugins every time, and they may not even work, so would it be possible for you to kindly update these plugins?

**Comment by Molli2967832506** [comment]
Such as ControlNet, PoseX, or Depth Library.

**Comment by acheong08** [comment]
Good suggestion. I'll look into bringing in ControlNet by default when I have time. If anyone wants to make a PR, that's welcome as well

**Comment by acheong08** [comment]
Done
