### ISSUE TITLE
Namerror

### ISSUE THREAD

**Issue by Vendetta-S** [acheong08/Diffusion-ColabUI#128]
![image](https://github.com/acheong08/Diffusion-ColabUI/assets/108780296/b77a3c33-4234-41a4-8d94-4cda558fbb29)
For some reason, as I used a model a default model which is AnythingV4.5, I always get this error for some reason

**Comment by acheong08** [comment]
Did you accidentally press clear model list?

**Comment by Vendetta-S** [comment]
Nope, I just pressed it but realized that I had to choose the same model again after resetting
