### ISSUE TITLE
Disconnecting itself

### ISSUE THREAD

**Issue by Vendetta-S** [acheong08/Diffusion-ColabUI#129]
For some reason, whenever I ignored the disk space error and continued, at some point it just disconnects itself

**Comment by Vendetta-S** [comment]
Oh you got to be kidding me

**Comment by Vendetta-S** [comment]
Welp, how long is it going to take to fix itself? never heard this issue coming up until now

**Comment by acheong08** [comment]
![18](https://github.com/acheong08/Diffusion-ColabUI/assets/36258159/d54fd227-dcc4-4722-ad58-b32c9736ebd1)

I'll look into it today. Will update

**Comment by acheong08** [comment]
I got it working

**Comment by acheong08** [comment]
Make sure to stay active on the colab site. Seems to be an issue with timeout

**Comment by acheong08** [comment]
Also fixed some numpy errors

**Comment by acheong08** [comment]
Going off the site for a few minutes kills the instance

**Comment by Vendetta-S** [comment]
> Going off the site for a few minutes kills the instance

Thanks for the info!
