### ISSUE TITLE
Quality seems worse than around a week ago

### ISSUE THREAD

**Issue by Enferlain** [acheong08/Diffusion-ColabUI#13]
Haven't used the colab in like 5 days and seems like there have been some updates to it. The thing I noticed right away is that default quality seems to be worse. Prompts and img2img seem to have similar results but the end product is lower in quality, like blurry/bad faces, hair, hands are almost always bad now, and other details that used to be fine.

Is there a way to test and compare to like October 20 and before vs oct 25? I don't think I'm tripping but I'd like to confirm.

Like here I'm using pretty much the same prompts but the quality is way different

![image](https://user-images.githubusercontent.com/15861396/197886385-03bf6ff3-f33c-4de0-b592-04ffeb3f5126.png)

**Comment by acheong08** [comment]
Three possible issues:
1. AUTOMATIC1111 added new optimizations that messed with things
2. The Vae.pt file is messing with things
3. Using the wrong model

Try running without animeVae and make sure to select NovelAI. Otherwise, there should be no difference as the models have remained unchanged. If there is an optimizer that lowers quality, check out issues in AUTOMATIC1111/stable-diffusion-webui

**Comment by Enferlain** [comment]
Tried running with just novelai enabled but still looks bad. Probably something with webui itself I guess. Checked open issues and [this](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/3630
) is the only similar thing I found

Unless something got enabled/disabled that now requires manual input to change, I have no clue and would probably struggle to find out what exactly.

**Comment by acheong08** [comment]
Fixed by AUTOMATIC

**Comment by Novapone** [comment]
How/where was it fixed?

**Comment by acheong08** [comment]
> How/where was it fixed?

Not by me. The problem was with the upstream WebUI

**Comment by acheong08** [comment]
See https://github.com/AUTOMATIC1111/stable-diffusion-webui

**Comment by Novapone** [comment]
Yes, obviously, but you have no idea what broke or when/where it was fixed? None of the other issues on the webui know either. You're the first to say it was fixed.

**Comment by acheong08** [comment]
Because it no longer spits out blurry images (Subjective and based on my own testing)

**Comment by acheong08** [comment]
If you continue to encounter the issue, feel free to make me reopen it
