### ISSUE TITLE
way to run on hugging face spaces?

### ISSUE THREAD

**Issue by nagaisa** [acheong08/Diffusion-ColabUI#14]
i see in the output about useing spaces for better reliablety. how can i do this

**Comment by acheong08** [comment]
Go to https://huggingface.co/spaces and press create new space. Then follow the given instructions.

Spaces allow you to run a model for 24/7. (I'm unsure of the costs.)

**Comment by nagaisa** [comment]
> Go to https://huggingface.co/spaces and press create new space. Then follow the given instructions.
> 
> Spaces allow you to run a model for 24/7. (I'm unsure of the costs.)

but what about the actual code part? how wolud i get the code from this repo to work on it?

**Comment by acheong08** [comment]
This repository would be irrelevant. You would want to use https://github.com/AUTOMATIC1111/stable-diffusion-webui/ directly with gradio. I haven't tried it out so I'm not exactly sure.
