### ISSUE TITLE
I Don't know what I'm doing wrong. Please help? (Loading VAE weights error)

### ISSUE THREAD

**Issue by PhoenixEugene** [acheong08/Diffusion-ColabUI#16]
I don't know why I get this error. It happens every time it reaches "Loading VAE weights from: /content/stable-diffusion-webui/models/Stable-diffusion/sd-v1-5.vae.pt"
It happens on both versions of the colab. Even the Stable one, as you can see in the first screenshot. It doesn't matter what else I pick in the 'models' section, as long as 'SDVae' is included, I get that error. I've been able to run the colab by just picking SD 1.5 since it's the one I prefer to use anyway, but I still can't help but wonder why I get this error. It must be something I'M doing because no one else has asked about this.

![2022-10-27 03_06_59-Greenshot](https://user-images.githubusercontent.com/54819253/199146379-511e7c96-1470-41a7-997b-7ce92203ab18.png)

This is what I get when I click on 'check dependencies'

![2022-11-01 03_48_52-Greenshot](https://user-images.githubusercontent.com/54819253/199147869-ab0dd80d-2390-455f-969c-39581059b218.png)

I don't know what any of this means. I'm sorry I'm really not that great with any of this.

**Comment by acheong08** [comment]
The error seems to be upstream. There are some issues with [acheong08/stable-diffusion-webui](https://github.com/acheong08/stable-diffusion-webui) that prevents the loading of 1.5 vae. I'll look into it.

**Comment by PhoenixEugene** [comment]
@acheong08 thank you so much!

**Comment by acheong08** [comment]
Update: It might be that the vae file provided by stabilityai has issues. RunwayML has also released the 1.5 vae. I will be seeing if that works

**Comment by acheong08** [comment]
Update: RunwayML licensing prevents wget without token. Using cloned version (possibly malicious. should be safe in colab)

**Comment by acheong08** [comment]
Doesn't work either. Must be issue with code rather than vae

**Comment by acheong08** [comment]
Error here https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/3316

Not yet fixed upstream. I have no idea how to fix it...

**Comment by acheong08** [comment]
I might have named the file wrong. (That feels like such a dumb issue)

**Comment by acheong08** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/1ed227b3b57f06f4152be3bfc9f83b0a839a2604/modules/sd_hijack_inpainting.py#L320

lmao

**Comment by acheong08** [comment]
Fixed in beta Colab. Will update stable once tested
