### ISSUE TITLE
Import error:

### ISSUE THREAD

**Issue by HerrTuulik** [acheong08/Diffusion-ColabUI#17]
File "/content/stable-diffusion-webui/repositories/stable-diffusion/ldm/models/diffusion/ddpm.py", line 19, in <module>
    from pytorch_lightning.utilities.distributed import rank_zero_only
ImportError: cannot import name 'rank_zero_only' from 'pytorch_lightning.utilities.distributed' (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/distributed.py)

It was working fine yesterday, but today can't get any version to run.

**Comment by acheong08** [comment]
Seems to be a dependency error. pytorch might be outdated on Google Colab. Looking into it now

**Comment by acheong08** [comment]
It seems Google Colab now lacks GPU environment variables. Trying to fix that somehow

**Comment by acheong08** [comment]
Not sure what's wrong with Google but they sabotaged GPU detection and messed up torch versions. The default Python version has also regressed to 3.7 when it was once 3.8. It'll take a while to patch everything up.

**Comment by acheong08** [comment]
I have isolated the issue to a single incorrect import statement. I wrote a temporary patch for it and it should work now. I will attempt to make a pull request with the fix upstream.

**Comment by acheong08** [comment]
The error is here: https://github.com/CompVis/stable-diffusion/blob/69ae4b35e0a0f6ee1af8bb9a5d0016ccb27e36dc/ldm/models/diffusion/ddpm.py#L19

**Comment by acheong08** [comment]
I have fixed it upstream within my own fork. CompVis is unlikely to patch this.

**Comment by Dantist333** [comment]
Hello. Help me please. Faced a problem. The day before yesterday, the neural network worked, and then at startup it began to give an error:

ImportError: cannot import name 'rank_zero_only' from 'pytorch_lightning.utilities.distributed' (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/distributed.py)

Refreshing the page and delete runtime don't work( My friend and other people say that everything works for them, but I have this error.

**Comment by acheong08** [comment]
@Dantist333 Are you using the stable version or beta version?

**Comment by Dantist333** [comment]
This error appears on both versions.

**Comment by acheong08** [comment]
Check the code and search for `git clone`.
If it's cloning from https://github.com/AUTOMATIC1111/stable-diffusion-webui, change it to https://github.com/acheong08/stable-diffusion-webui

**Comment by acheong08** [comment]
I have been testing it and it works. It might be that you have an outdated version of the Colab seeing as I just fixed the flaw yesterday

**Comment by Dantist333** [comment]
Possibly an outdated version. Can you please tell me how to update it?

**Comment by acheong08** [comment]
It should update automatically if you refresh. If it doesn't show the code and manually change 
`!git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui` to `!git clone https://github.com/acheong08/stable-diffusion-webui`

**Comment by acheong08** [comment]
![image](https://user-images.githubusercontent.com/36258159/199628504-ff3bfd56-a3ac-4513-9c39-34cc8cfd838c.png)

Use ctrl+f to find the part that says `git clone`

**Comment by acheong08** [comment]
![image](https://user-images.githubusercontent.com/36258159/199628569-33709eff-e131-4f6f-bb30-85a058ea719c.png)

**Comment by Dantist333** [comment]
![image](https://user-images.githubusercontent.com/117324399/199628736-70faf55a-0d3b-412f-ac62-cabc960fb4a9.png)
Seems like it is?

**Comment by acheong08** [comment]
Yes. Was it different before?

**Comment by Dantist333** [comment]
To be honest, this is my first time looking at this code. But two days ago, the neural network worked. And now this error

**Comment by acheong08** [comment]
> To be honest, this is my first time looking at this code. But two days ago, the neural network worked. And now this error

This is due to an update by CompVis upstream and I'm left cleaning up their mess

**Comment by Dantist333** [comment]
This error is only with me, but not my friends. Although our computers are similar in power.

**Comment by acheong08** [comment]
It's likely an issue of the Colab not updating. Perhaps you need to open it in Incognito. Did you attempt to save a copy of the Colab? That might also be the problem as copies don't update

**Comment by Dantist333** [comment]
No, I didn't save anything from the site. Maybe it's an old version, but I don't know how to update. Automatically it doesn't seem to do it(
Sorry for such stupid moments, but I almost don't understand anything about it.

**Comment by acheong08** [comment]
It should work now. Try running it again.

> ![image](https://user-images.githubusercontent.com/117324399/199628736-70faf55a-0d3b-412f-ac62-cabc960fb4a9.png) Seems like it is?

**Comment by Dantist333** [comment]
![image](https://user-images.githubusercontent.com/117324399/199629645-13c3ff08-c1ad-45d0-a29f-a661115b969e.png)
![image](https://user-images.githubusercontent.com/117324399/199629675-178ef676-f4b1-4ef5-aebb-004f110e4e67.png)
Unfortunately no change

**Comment by Dantist333** [comment]
I clicked "disconnect from the runtime and remove it".
Then, in the upper right corner, click "connect".
Launched the neural network, the error came out again:
![image](https://user-images.githubusercontent.com/117324399/199630349-eb57d9c8-d922-4ddb-899b-d83f0ef4a419.png)

Perhaps I'm doing something wrong?

**Comment by Dantist333** [comment]
I'll try again and reload the page

**Comment by acheong08** [comment]
Check if you see these two lines of code. if you don't keep refreshing or something until you do:
![image](https://user-images.githubusercontent.com/36258159/199630542-132f5cd5-af72-439e-b304-047e5ea34e97.png)

It will fix the issue manually

**Comment by Dantist333** [comment]
![image](https://user-images.githubusercontent.com/117324399/199630775-e558e4a7-da6f-4a64-8b98-43e9dd0b19ef.png)
No, I don't have these lines.

**Comment by acheong08** [comment]
I have no idea what is going on. Can't replicate. Perhaps try in incognito with another account

**Comment by acheong08** [comment]
![image](https://user-images.githubusercontent.com/36258159/199631792-509c9868-4e74-431b-9ada-faad9966c8c3.png)

**Comment by Dantist333** [comment]
Logged in incognito mode to another account from another browser
![image](https://user-images.githubusercontent.com/117324399/199631777-0eeb7d29-5597-4a99-a952-01a26e8ef5d3.png)
![image](https://user-images.githubusercontent.com/117324399/199632214-33972853-d8ad-4fa1-ac46-ceb08fafd555.png)
![image](https://user-images.githubusercontent.com/117324399/199632260-d49442ed-b64a-440c-9edc-f5c34b83bd3d.png)
![image](https://user-images.githubusercontent.com/117324399/199632285-1aa5260b-a7a5-45f3-832e-476571f3400a.png)


It's just some kind of curse...

**Comment by acheong08** [comment]
I can't fix an issue I cannot replicate. Perhaps ask your friends to help. I'm sorry

**Comment by Dantist333** [comment]
Alright, thanks for your help and your time.

**Comment by Dantist333** [comment]
WaifuDiffusion is stable. It's just about this new neural network

**Comment by acheong08** [comment]
SD1.5? Perhaps there are other optimizations I am unaware of. 

> WaifuDiffusion is stable. It's just about this new neural network
