### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Seth-spec** [acheong08/Diffusion-ColabUI#18]
I just checked NovelAI model and I got this error :(
![error](https://user-images.githubusercontent.com/56384900/199267315-ebb1561f-efdd-46b1-b9b1-b3bf0822cc53.png)

I got this error when I tried to run dependencies
![depend](https://user-images.githubusercontent.com/56384900/199267602-42c8bba6-bb41-4ae5-b011-9a313f80d146.png)

**Comment by acheong08** [comment]
Refresh. It has just been fixed
