### ISSUE TITLE
Feature request: non gradio version.

### ISSUE THREAD

**Issue by possom2009** [acheong08/Diffusion-ColabUI#19]
Is it possible to have a non gradio version? Sessions always disconnect after a bit if I don't go back to the colab page.

**Comment by acheong08** [comment]
There was a localtunnel version previously but it was removed after some were complaining it was unnecessary. 

Regarding the session disconnect, are you referring to Gradio's 24 hour limit or Google Colab's 12 hour limit for free tier.

If you are not a paying customer of Google, there are a few limits that I cannot resolve:
- 12 hour hard limit. Your session will disconnect no matter what in 12 hours
- 2 hour idle limit. You will be disconnected if the GPU is not used for 2 hours
- Arbitrary limits based on demand. If there is a lack of resources, paying users will be prioritized.

**Comment by possom2009** [comment]
The colab page resets and deletes everything if I don't click the tab it's open in on the browser after a bit. 

As for non gradio, I was thinking something like the Inference section of this colab. 
[Neo Hidamari](https://colab.research.google.com/drive/1AfAmwLMd_Vx33O9IwY2TmO9wKZ8ABRRa)

**Comment by acheong08** [comment]
> The colab page resets and deletes everything if I don't click the tab it's open in on the browser after a bit.

This is a limitation set by Google Colab. I cannot fix this.

**Comment by acheong08** [comment]
> As for non gradio, I was thinking something like the Inference section of this colab. [Neo Hidamari](https://colab.research.google.com/drive/1AfAmwLMd_Vx33O9IwY2TmO9wKZ8ABRRa)

I don't really understand what you mean by non-gradio. Do you want the interface to be built into Colab?

**Comment by acheong08** [comment]
NOP made a really good interface within [Google Colab ](https://colab.research.google.com/drive/1jUwJ0owjigpG-9m6AI_wEStwimisUE17?ref=dtf.ru)for Stable Diffusion if that's what you're looking for.

**Comment by acheong08** [comment]
Alternatives available. This repository exists for WebUI usage. For Colab usage, see the above comment.

Gradio restrictions are irrelevant unless you are paying for Google Colab. In which case I can reopen this issue.
