### ISSUE TITLE
Codeformer error

### ISSUE THREAD

**Issue by possom2009** [acheong08/Diffusion-ColabUI#21]
Edit: Deleted repositories from g drive solved the problem.

I'm not sure what the problem is:

/content/drive/MyDrive/AI/stable-diffusion-webui
Python 3.7.15 (default, Oct 12 2022, 19:14:55) 
[GCC 7.5.0]
Commit hash: fff7808311bdf414e8c5263a4383d170dc31709e
Installing gfpgan
Installing clip
Cloning K-diffusion into repositories/k-diffusion...
Fetching updates for CodeFormer...
Checking out commit for CodeFormer with hash: c5b4593074ba6214284d6acd5f1719b6c5d739af...
Traceback (most recent call last):
  File "launch.py", line 251, in <module>
    prepare_enviroment()
  File "launch.py", line 203, in prepare_enviroment
    git_clone(codeformer_repo, repo_dir('CodeFormer'), "CodeFormer", codeformer_commit_hash)
  File "launch.py", line 82, in git_clone
    run(f'"{git}" -C {dir} checkout {commithash}', f"Checking out commit for {name} with hash: {commithash}...", f"Couldn't checkout commit {commithash} for {name}")
  File "launch.py", line 34, in run
    raise RuntimeError(message)
RuntimeError: Couldn't checkout commit c5b4593074ba6214284d6acd5f1719b6c5d739af for CodeFormer.
Command: "git" -C repositories/CodeFormer checkout c5b4593074ba6214284d6acd5f1719b6c5d739af
Error code: 128
stdout: <empty>
stderr: fatal: reference is not a tree: c5b4593074ba6214284d6acd5f1719b6c5d739af

**Comment by acheong08** [comment]
Have you resolved this?

**Comment by acheong08** [comment]
Not replicated

**Comment by possom2009** [comment]
> Not replicated

It was an issue with corrupted files in the repositories folder in gdrive. Fixed by deleting the said files and restarting the process over.
