### ISSUE TITLE
Naifu-Diffusion request

### ISSUE THREAD

**Issue by watercup0926** [acheong08/Diffusion-ColabUI#22]
Please add Naifu-Diffusion (4chan ver.)into this project cause i think it goes well.
And please let me know is there any technical problem(but i can`t help sry)

**Comment by acheong08** [comment]
Any idea where I might find the model?

**Comment by acheong08** [comment]
Ah. After a bit of research, it seems Naifu is simply an interface for NovelAI. The model itself is exactly the same. Everything Naifu has, stable-diffusion-webui also has

**Comment by acheong08** [comment]
The leaked NovelAI is the 4chan ver. There is no other version

**Comment by acheong08** [comment]
Please let me know if I've gotten something wrong

**Comment by acheong08** [comment]
![image](https://user-images.githubusercontent.com/36258159/200855828-544ac317-544f-428b-9bc3-751e2e7526b3.png)


I have retrieved the torrent. It uses the same model, hypernetworks, and vae. The difference is in the use of OpenAI's clip and sentence transformers. However, these features have already been implemented here: https://github.com/acheong08/stable-diffusion-webui

**Comment by watercup0926** [comment]
oh thanks (although I don't fully understand)

**Comment by acheong08** [comment]
Closing this as it's not the most relevant.
