### ISSUE TITLE
Zeipher F222 Female Nude Model Request? Please?

### ISSUE THREAD

**Issue by PhoenixEugene** [acheong08/Diffusion-ColabUI#23]
I apologize if this is not the right place to post this. I have been thinking about requesting this model for a few days now but my anxiety never allowed me to. You'd already provided us with so much good stuff as it is and I didn't wanna be annoying and ask for more. But then I saw that you were more than open to the idea of adding new models and I thought I'd grow some balls and ask if it's possible to consider mine.

Basically, the F222 is a newly released NSFW model by Zeipher that's exclusively trained on the (realistic) naked female form. Compared to other models out there, the F222 produces far better and much more anatomically correct results. I will be eternally grateful if you'd consider adding it to the roster!

Rentry link: https://rentry.org/sdmodels#zeipher-f222-female-nude-better-anatomy
Here's their official website with multiple links for the model and a link to their discord for more info: https://ai.zeipher.com/

**Comment by acheong08** [comment]
This is the correct place to post requests. I will look into this and add it when I have the time (I'm having online classes right now haha)

**Comment by acheong08** [comment]
I'm downloading the model now. It might take a while to get it onto huggingface (Which has faster download speeds)

**Comment by acheong08** [comment]
I have added the model on the Colab. Currently testing. Will push once functional (I will not test quality of NSFW content but I will see if it loads and can generate hello world without bugs)

**Comment by acheong08** [comment]
Note that recently uploaded models have slower download speeds

**Comment by acheong08** [comment]
Downloading: ✅
Loading weights: ✅
Generation: ✅

Request completed

**Comment by acheong08** [comment]
@PhoenixEugene Try it out.

**Comment by acheong08** [comment]
I don't have the time to search for new models. If any catch your interest, please do let me know.

**Comment by PhoenixEugene** [comment]
@acheong08 I LOVE YOU! Omg, you made me so happy lmao. Ok, I'm about to test it right now. I'll come back and let you know how it went!

**Comment by PhoenixEugene** [comment]
Work great! @acheong08 Again, thank you so much!
