### ISSUE TITLE
A way to use custom embeddings?

### ISSUE THREAD

**Issue by qwertea** [acheong08/Diffusion-ColabUI#24]
Is there/would you consider adding a method to use the custom premade embedding and hypernetwork files I can find on the internet?

**Comment by acheong08** [comment]
You can drag and drop embeddings via the files tab in Colab. If you are capable, perhaps make a pull request at https://github.com/acheong08/stable-diffusion-webui to do that within the UI itself.

**Comment by acheong08** [comment]
I might work on this if I have time. (currently a bit busy)

**Comment by qwertea** [comment]
Oh, thanks! Since it's possible to do so with Colab, it's fine.
