### ISSUE TITLE
It gives an error when I try to load a model from huggingface

### ISSUE THREAD

**Issue by RayZ3R0** [acheong08/Diffusion-ColabUI#31]
Im not sure if I am doing this right, but I'm trying to load a model from huggingface but it just isnt working
![image](https://user-images.githubusercontent.com/69317757/201479611-53fb25f6-03b5-49e9-af16-019f8c905628.png)
![image](https://user-images.githubusercontent.com/69317757/201479626-8592f7c4-c48c-4d78-bca6-0da30488453f.png)

**Comment by acheong08** [comment]
You need to link to the actual download file

**Comment by acheong08** [comment]
For your specific model, it's here: https://huggingface.co/SpiteAnon/gigachad-diffusion/resolve/main/gigachad_2000.ckpt

**Comment by acheong08** [comment]
I will add better documentation

**Comment by acheong08** [comment]
Note that dreambooth models may not work properly

**Comment by acheong08** [comment]
Dreambooth details here: https://github.com/d8ahazard/sd_dreambooth_extension

**Comment by acheong08** [comment]
Dreambooth models work too it seems

**Comment by acheong08** [comment]
![image](https://user-images.githubusercontent.com/36258159/201481694-490ec64e-2365-4690-9458-58bd99f8ffaa.png)
I have got it working with  https://huggingface.co/SpiteAnon/gigachad-diffusion/resolve/main/gigachad_2000.ckpt as the URL

**Comment by acheong08** [comment]
Damn this model is insane. The outputs are very consistent

**Comment by RayZ3R0** [comment]
oh, thanks. It worked now
