### ISSUE TITLE
I am once again here to request a new NSFW model: [HassansBlend1.2] 

### ISSUE THREAD

**Issue by PhoenixEugene** [acheong08/Diffusion-ColabUI#32]
Name: HassanBlend1.2
Description: Hey acheong, I am once again here to request a new NSFW model. It's a mix of multiple models (including SD1.5, NAI, R34, F222, AnythingV3, and much, much more). I couldn't add it myself as a custom model because it's not hosted over at huggingface and google drive links don't work. So if it's not too much trouble, it would mean a lot if you'd add this model to the already amazing roster. You can find all kinds of information in the link below. All the models merged, some image samples, prompting examples, and of course; links to download the model itself.
URL: https://rentry.org/sdhassan

**Comment by acheong08** [comment]
As a niche blend, I will not directly add this as a default model. However, I will upload it to huggingface so that you may add it as a custom model.
It is troublesome that there is no proper download link as Google Drive and Mega don't really work well for me.

**Comment by acheong08** [comment]
I am getting an error downloading the file 
```
Access denied with the following error:

 	Too many users have viewed or downloaded this file recently. Please
	try accessing the file again later. If the file you are trying to
	access is particularly large or is shared with many people, it may
	take up to 24 hours to be able to view or download the file. If you
	still can't access a file after 24 hours, contact your domain
	administrator. 
```
If possible, could you upload it onto huggingface yourself?

**Comment by acheong08** [comment]
I copied the file to my own drive and currently uploading to huggingface. Might add it to the default list because why not

**Comment by acheong08** [comment]
I have uploaded the model to huggingface. I have created an issue to keep track of some custom models in case people want them. https://github.com/acheong08/Diffusion-ColabUI/issues/33#issuecomment-1312636695

You can add custom models here
![image](https://user-images.githubusercontent.com/36258159/201505760-171b40d5-f199-4d8e-bd5b-aeabf5541234.png)

**Comment by PhoenixEugene** [comment]
Thank you so much! And sorry for the trouble!
