### ISSUE TITLE
Custom models list

### ISSUE THREAD

**Issue by acheong08** [acheong08/Diffusion-ColabUI#33]
I cannot add everything into the default models as it is meant to be clean.

I ask that you some links to niche models here with their name and direct download URL. You can upload them to huggingface yourself if they're not already available there.

**Comment by acheong08** [comment]
HassansBlend: https://huggingface.co/acheong08/HassansBlend/resolve/main/HassansBlend.ckpt

GigaChad: https://huggingface.co/SpiteAnon/gigachad-diffusion/resolve/main/gigachad_2000.ckpt

**Comment by BrushieBuns** [comment]
Would you possibly be able to add the ability to load .ckpt file models from google drive as well? I have some that aren't on huggingface and haven't been able to figure out any solution beyond uploading them there, but the models aren't mine.

**Comment by acheong08** [comment]
I can. I'll implement it today

**Comment by acheong08** [comment]
@BrushieBuns I have added the functionality. It will automatically detect when you enter a Google Drive URL and download it from there.

**Comment by sknn23** [comment]
> @BrushieBuns I have added the functionality. It will automatically detect when you enter a Google Drive URL and download it from there.

![MKDCSPQ@AHW`E 8TK} J`(J](https://user-images.githubusercontent.com/116281060/202850637-10028af9-bb9a-4934-8acf-777d1d43c71a.png)
![`L(I3KAZ9R9}T06YS6AC_WR](https://user-images.githubusercontent.com/116281060/202850639-97b25c21-28a5-498c-827f-03205a42b417.png)
when i run Start WebUI, "&id=1AnFSNuCvzfLk4IvD7sTyCh2PZlZwkxAd" of Google Drive URL is missing, Only left "https://drive.google.com/uc?export=download"

**Comment by acheong08** [comment]
Ah. I see the issue. Fixing it now

**Comment by acheong08** [comment]
@sknn23 The format for your URL is wrong

**Comment by acheong08** [comment]
It should be: https://drive.google.com/file/d/<ID>/view?usp=sharing

**Comment by acheong08** [comment]
So 1AnFSNuCvzfLk4IvD7sTyCh2PZlZwkxAd would be https://drive.google.com/file/d/1AnFSNuCvzfLk4IvD7sTyCh2PZlZwkxAd/view?usp=sharing

**Comment by acheong08** [comment]
Nvm I was wrong

**Comment by acheong08** [comment]
Let me fix a few things

**Comment by acheong08** [comment]
Fixed

**Comment by sknn23** [comment]
> Fixed

thank you

**Comment by acheong08** [comment]
Stale
