### ISSUE TITLE
I cannot seem to find the textual inversion tab

### ISSUE THREAD

**Issue by RayZ3R0** [acheong08/Diffusion-ColabUI#37]
Hello, I would like to use textual inversion but I can't seem to find the tab in the UI. I have seen some youtube videos where there's a tab named textual inversion. Is the UI outdated or something?

**Comment by acheong08** [comment]
The YouTube videos are outdated.

**Comment by acheong08** [comment]
It should be under Training

**Comment by acheong08** [comment]
It is concerning that automatic1111 hasn't been active for almost a week. The upstream UI might have been abandoned

**Comment by acheong08** [comment]
![image](https://user-images.githubusercontent.com/36258159/202233814-189ff0c3-d401-462b-82ed-c2863ea863c5.png)

**Comment by RayZ3R0** [comment]
oh,thanks!
