### ISSUE TITLE
Problem logging in gradio

### ISSUE THREAD

**Issue by lifame** [acheong08/Diffusion-ColabUI#41]
When you try to enter the interface using the link to gradio, it gives an empty window.

![image](https://user-images.githubusercontent.com/85097581/203802768-d60f1b25-da96-4bdd-9ca9-5f5ffaa7a424.png)

**Comment by acheong08** [comment]
Could your firewall be blocking it? Gradio should work. Can't replicate.

**Comment by acheong08** [comment]
Internet issue probably
