### ISSUE TITLE
WebUI setup completes successfully without generating a Gradio link

### ISSUE THREAD

**Issue by aeiouaeiouaeiouaeiouaeiouaeiou** [acheong08/Diffusion-ColabUI#44]
Everything was still working fine this morning.

![image](https://user-images.githubusercontent.com/69355938/204130187-7a0a6459-b7dd-47aa-812f-3c52c637875f.png)

**Comment by acheong08** [comment]
This is a memory issue. https://stackoverflow.com/questions/48750199/google-colaboratory-misleading-information-about-its-gpu-only-5-ram-available

You have been placed on their blacklist.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
Thanks for the reply, it's sad that they don't message about it.
