### ISSUE TITLE
gateway timeout

### ISSUE THREAD

**Issue by liqira** [acheong08/Diffusion-ColabUI#45]
Encounter this error when trying to run the Colab:

requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/openai/clip-vit-large-patch14/resolve/main/vocab.json

**Comment by acheong08** [comment]
Huggingface is down! https://status.huggingface.co/

**Comment by acheong08** [comment]
It's back up
