### ISSUE TITLE
ERROR: xformers-0.0.14.dev0-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by meequz** [acheong08/Diffusion-ColabUI#47]
It started to happen today with any model.
`ERROR: xformers-0.0.14.dev0-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform.` - when running "Start WebUI" cell. After that WebUI starts, but generation doesn't work. I have not saved the traceback, but the exception occured somewhere inside xformers.

**Comment by misobarisic** [comment]
This is happening since the python version colab uses has been updated to 3.8 from the previous 3.7. This means we need a fresh build of xfrormers. Building it right now. Will make a pr if successful

**Comment by acheong08** [comment]
> This is happening since the python version colab uses has been updated to 3.8 from the previous 3.7. This means we need a fresh build of xfrormers. Building it right now. Will make a pr if successful

Thank you

**Comment by acheong08** [comment]
fixed

**Comment by meequz** [comment]
I haven't expected such speed in issue resolving! Just wow. Thank you everyone
