### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'pop'

### ISSUE THREAD

**Issue by Rorutop** [acheong08/Diffusion-ColabUI#48]
I just got this error just by having 4 models. Im sure it runs forever
![image](https://user-images.githubusercontent.com/66291382/205256990-ad0d5ec8-f7a3-49d7-be1d-123f51cd87d7.png)

**Comment by Rorutop** [comment]
Well now it says "EOFError: Ran out of input" anddd it just stops.

**Comment by acheong08** [comment]
Restart runtime. You might have run out of disk storage

**Comment by Rorutop** [comment]
Okay its working now thanks!! just switched account and removed 1 model

**Comment by acheong08** [comment]
👍
