### ISSUE TITLE
TypeError: memory_efficient_attention() got an unexpected keyword argument 'attn_bias'

### ISSUE THREAD

**Issue by McRoyce** [acheong08/Diffusion-ColabUI#5]
This messages appears when I clicked generate

TypeError: memory_efficient_attention() got an unexpected keyword argument 'attn_bias'
Time taken: 7.27s
Torch active/reserved: 1677/1722 MiB, Sys VRAM: 2784/15110 MiB (18.42%)
![Screenshot 2022-10-20 at 15-05-35 Stable Diffusion](https://user-images.githubusercontent.com/94728369/196892252-d209260b-c75b-41e3-bb04-23bb00bb9cbe.png)

**Comment by acheong08** [comment]
Probably comes from AUTOMATIC1111/stable-diffusion-webui. Open an issue there.

**Comment by acheong08** [comment]
Unable to reproduce.

**Comment by acheong08** [comment]
Do you mind sharing what settings or options you chose?

**Comment by acheong08** [comment]
Edge case

**Comment by jurassicjordan** [comment]
im having this issue where do I find this vae.pt file?

**Comment by tomkolron** [comment]
i got the same problem on the webgui

**Comment by acheong08** [comment]
https://huggingface.co/acheong08/secretAI/resolve/main/stableckpt/animevae.pt

https://huggingface.co/stabilityai/sd-vae-ft-mse-original/resolve/main/vae-ft-mse-840000-ema-pruned.ckpt
