### ISSUE TITLE
.safetensors files

### ISSUE THREAD

**Issue by qwertea** [acheong08/Diffusion-ColabUI#53]
I was trying to use the new V3 of Elysium-Anime but it doesn't work.
https://huggingface.co/hesw23168/SD-Elysium-Model/blob/main/Elysium_Anime_V3.safetensors

Launching Web UI with arguments: --share --xformers --enable-insecure-extension-access --vae-path /content/stable-diffusion-webui/models/Stable-diffusion/novelAI.vae.pt --lowvram --gradio-auth webui:diffusion
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Downloading: 100% 939k/939k [00:01<00:00, 721kB/s]
Downloading: 100% 512k/512k [00:01<00:00, 464kB/s]
Downloading: 100% 389/389 [00:00<00:00, 354kB/s]
Downloading: 100% 905/905 [00:00<00:00, 847kB/s]
Downloading: 100% 4.41k/4.41k [00:00<00:00, 3.70MB/s]
Downloading: 100% 1.59G/1.59G [00:20<00:00, 82.9MB/s]
Loading weights [1a97f4ef] from /content/stable-diffusion-webui/models/Stable-diffusion/elysium-v3.ckpt
Error verifying pickled file from /content/stable-diffusion-webui/models/Stable-diffusion/elysium-v3.ckpt:
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/safe.py", line 81, in check_pt
    with zipfile.ZipFile(filename) as z:
  File "/usr/lib/python3.8/zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by acheong08** [comment]
This is because you are using blob. Use the resolve URL for LFS files:
https://huggingface.co/hesw23168/SD-Elysium-Model/resolve/main/Elysium_Anime_V3.safetensors

**Comment by qwertea** [comment]
Nope, I did use the resolve link in the colab, I just linked the blob in the issue so you could check the file details and stuff.

`('elysium-v3', 'https://huggingface.co/hesw23168/SD-Elysium-Model/resolve/main/Elysium_Anime_V3.safetensors', 'None')`

**Comment by acheong08** [comment]
Ok. I will look into this

**Comment by acheong08** [comment]
Found the issue to be https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/4930

Need to name safetensors properly. Fixing now
