### ISSUE TITLE
error

### ISSUE THREAD

**Issue by PutraCoud** [acheong08/Diffusion-ColabUI#54]
RuntimeError: No such operator xformers::efficient_attention_forward_cutlass - did you forget to build xformers with `python setup.py develop`?

Interrupted with signal 2 in <frame at 0x7fcdddad2520, file '/content/stable-diffusion-webui/webui.py', line 108, code wait_on_server>

**Comment by acheong08** [comment]
Fixed in https://colab.research.google.com/github/acheong08/Diffusion-ColabUI/blob/main/Diffusion_WebUI.ipynb

Moving away from clones.
