### ISSUE TITLE
Gdrive error

### ISSUE THREAD

**Issue by PutraCoud** [acheong08/Diffusion-ColabUI#56]
RedirectMissingLocation                   Traceback (most recent call last)
[<ipython-input-10-936146e4c5bd>](https://localhost:8080/#) in <module>
     47   gauth.credentials = GoogleCredentials.get_application_default()
     48   drive = GoogleDrive(gauth)
---> 49   file_id = upload_file('/content/output.zip', create_folder(folder_name), save_as)
     50   print("Your sharing link: https://drive.google.com/file/d/" + file_id + "/view?usp=sharing")

11 frames
[/usr/local/lib/python3.8/dist-packages/httplib2/__init__.py](https://localhost:8080/#) in _request(self, conn, host, absolute_uri, request_uri, method, body, headers, redirections, cachekey)
   1683                 if redirections:
   1684                     if "location" not in response and response.status != 300:
-> 1685                         raise RedirectMissingLocation(
   1686                             _(
   1687                                 "Redirected but the response is missing a Location: header."

RedirectMissingLocation: Redirected but the response is missing a Location: header.

**Comment by acheong08** [comment]
Needs updated library. Fixing
