### ISSUE TITLE
Shows a ^C then stops

### ISSUE THREAD

**Issue by RayZ3R0** [acheong08/Diffusion-ColabUI#57]
I'm getting this ^C in the last line then it stops. I haven't touched anything so I don't get why its terminating it everytime. Sometimes it works when I use a different google account
![image](https://user-images.githubusercontent.com/69317757/206697493-12769f75-91db-426b-b0ba-e52e581dcb25.png)

**Comment by acheong08** [comment]
Sometimes Google limits your VRAM. It is close to random and I have no idea how Google decides which accounts to greylist

**Comment by RayZ3R0** [comment]
Ah, alright
