### ISSUE TITLE
High Vram usage and UI issues

### ISSUE THREAD

**Issue by Vendetta-S** [acheong08/Diffusion-ColabUI#58]
The High Vram usage I have been experiencing never really happen and the UI issues didn't bother me, until recently. I did the same thing and yesterday it worked but now something is off.
The unusual high vram usage I am seeing when it starts to generate and while it's generating too.
![image](https://user-images.githubusercontent.com/108780296/207599834-4766550e-4070-4bfa-b013-f2ade51ef91d.png)
(The orange peak happened when it was done generating and decoded the images)
I know it didn't peak like this, before I screenshotted the image I did my normal AI generating and it peaked on the RED (which means it used almost all of the Vram).
And the UI is broken too, it stops halfway when I was generating it and it always happens if I used the High res fix.
![image](https://user-images.githubusercontent.com/108780296/207600584-54495854-570c-4069-92d9-3520bb55883a.png)
The High Vram usage might be the model or the server or even colab but the UI one is really annoying.

**Comment by acheong08** [comment]
Regarding the high vram usage, you can enable `--medvram` in the vram options.

Gradio is unstable for an unknown reason. It will take some time to figure out

**Comment by Enferlain** [comment]
Yeah the ui thing is really weird, some days I get 0 issues, today it gets stuck on every normal generation.

**Comment by Vendetta-S** [comment]
Apologies if I didn't respond quickly, but I noticed this isn't a isolated incident. I tested another colab and it had the same issues as this one, assuming that other colabs are the same that means this is something from either AUTOMATIC1111's github or gradio itself.
And Yes, I did use the `--medvram` option but it still takes majority of the Vram. But, I still don't know why and for that reason I will close this issue as something not fixable as well as the UI issue coming from the aforementioned AUTOMATIC1111's github or gradio.

**Comment by acheong08** [comment]
I have tested this myself and verified that it is a universal issue. Gradio is currently experiencing extremely high demand which causes some network issues. Automatic's repo doesn't handle these errors well which is why it gets stuck. 

> And Yes, I did use the --medvram option but it still takes majority of the Vram. But, I still don't know why it happened. I'll close this issue if the UI issues and Vram issues still persist.

This seems to be caused new code in Automatic's repo. Difficult to fix from my end but it'll check it out

**Comment by Vendetta-S** [comment]
Decided to run it and this happened:
![image](https://user-images.githubusercontent.com/108780296/207856048-7d5a4650-a76d-4e22-a819-ffb6f206a99b.png)
Well crap. Somehow GFPGAN decided to not work anymore.

**Comment by Vendetta-S** [comment]
And another issue:
![image](https://user-images.githubusercontent.com/108780296/207866103-e9faf58a-e3c7-4455-93bf-bce07b44a0aa.png)
Since multiple issues have been reported, I'll split these two issues into a separate issue page for later fixing.

**Comment by Vendetta-S** [comment]
The high Vram usage isn't nearly problematic now but it still peaks at the orange peaks. For now, it seems like the only issue here is the high Vram one.
