### ISSUE TITLE
Decided to run it and this happened:

### ISSUE THREAD

**Issue by Vendetta-S** [acheong08/Diffusion-ColabUI#59]
Decided to run it and this happened:
![image](https://user-images.githubusercontent.com/108780296/207856048-7d5a4650-a76d-4e22-a819-ffb6f206a99b.png)
Well crap. Somehow GFPGAN decided to not work anymore.
I run it again and the error didn't happen. And, another error happened and CLIP didn't want to work.
![image](https://user-images.githubusercontent.com/108780296/207857047-5cb39725-18f0-430a-9f1f-aac3cb329a90.png)
And it decided to work again.

_Originally posted by @Vendetta-S in https://github.com/acheong08/Diffusion-ColabUI/issues/58#issuecomment-1352971681_

**Comment by acheong08** [comment]
This looks like a temporary outage of GitHub. It should probably be resolved by now.

**Comment by acheong08** [comment]
The error says it's unable to connect to GitHub

**Comment by acheong08** [comment]
You're not the only one encountering this: https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/5767
