### ISSUE TITLE
And another issue:

### ISSUE THREAD

**Issue by Vendetta-S** [acheong08/Diffusion-ColabUI#60]
And another issue:
![image](https://user-images.githubusercontent.com/108780296/207866103-e9faf58a-e3c7-4455-93bf-bce07b44a0aa.png)
Since multiple issues have been reported, I'll split these two issues into a separate issue page for later fixing.

_Originally posted by @Vendetta-S in https://github.com/acheong08/Diffusion-ColabUI/issues/58#issuecomment-1353033522_

**Comment by acheong08** [comment]
It's a gradio issue. It looks like demand is too high and they ran out of ports for connection. They are unable to tunnel the connection.

**Comment by acheong08** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/2937
