### ISSUE TITLE
Having issues with gfpgan

### ISSUE THREAD

**Issue by SFMAmateur** [acheong08/Diffusion-ColabUI#61]
Greetings, I am attempting to install the stable diffusion in my computer, yet I am running on this error.
![image](https://user-images.githubusercontent.com/14806249/207963063-4fed7e19-c4d9-4598-8e35-3daf37802263.png)
Does anyone have any idea what could be the case? I am installing it on an external hard drive, but I don't think this could be the issue. I have Python 3.10.6 and git installed, also properly inserted in PATH, despite the error message claiming that Windows cannot recognize it as an internal or external command.

My **webui-user** looks like this:
![image](https://user-images.githubusercontent.com/14806249/207963385-7515bfda-d7a9-4532-95e2-8262739234d4.png)

**How did I reproduce this issue:**
_I merely opened webui-user file, and it seems to be unable to install gfpgan._

Thank you for your attention!

**Comment by acheong08** [comment]
Wrong place. Look at https://github.com/AUTOMATIC1111/stable-diffusion-webui

**Comment by SFMAmateur** [comment]
> Wrong place. Look at https://github.com/AUTOMATIC1111/stable-diffusion-webui

Sorry!
