### ISSUE TITLE
Question about the VAE options

### ISSUE THREAD

**Issue by PhoenixEugene** [acheong08/Diffusion-ColabUI#67]
In previous versions of the Colab, you were able to select both VAE files at the same time by ticking their boxes; Anime VAE and SD VAE. Now it's a drop-down menu where you can only select one, the other, or neither. I just wanted to ask if that is intentional and if by not selecting one, both end up loading instead? Basically, if I want to use both, should I leave the selection empty?

**Comment by acheong08** [comment]
It is intentional. You can only apply a single VAE at a time. In previous versions, if you tried selecting multiple, only one would be applied anyways.

**Comment by PhoenixEugene** [comment]
Ah! I didn't know that. Thank you for the clarification!
