### ISSUE TITLE
Colab link does not appear

### ISSUE THREAD

**Issue by TheDuckWithAMonocle** [acheong08/Diffusion-ColabUI#72]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/6210
stable-diffusion-webui somehow managed to break the --share flag. 

a temporary fix is adding `!git checkout 11d432d` after the working directory has been set to stable-diffusion-webui

**Comment by acheong08** [comment]
Fixed (for now)

**Comment by qwertea** [comment]
This issue is fixed now so you can go ahead and remove the line.

**Comment by acheong08** [comment]
Done
