### ISSUE TITLE
Generated images not showing

### ISSUE THREAD

**Issue by mathvafter** [acheong08/Diffusion-ColabUI#75]
when using sampling steps greater than 26, the results are not showing
try to click generate button again but its no response
generated results can be seen on the collab folder, but in the WebUI cannot be seen

**Comment by acheong08** [comment]
Issue with gradio bandwidth limits. Can't transmit over 2MB at once if I remember correctly

**Comment by Vendetta-S** [comment]
Is this problem going to persist or do we have to wait for it? because this never really happen, I did once downloaded something that was beyond 2MB.
Either this is another waiting or a annoying one

**Comment by acheong08** [comment]
It seems the connection just breaks on the server end. It worked for a few weeks but it no longer works. I guess you have to try keeping the size lower. Another alternative is to view it in the image history/browser. I think it renders there sometimes.

**Comment by acheong08** [comment]
I haven't found a good solution to this with gradio. localtunnel was once preferred but it was discontinued due to instability

**Comment by acheong08** [comment]
Maybe ngrok will work but it will force users to get a token which is extra work

**Comment by Vendetta-S** [comment]
I'll just wait until it is fixed.

**Comment by qwertea** [comment]
Hi, I don't know the details but this is only a problem with the newer version of gradio. When I downgrade it `3.13.0` by editing `requirements.txt` and `requirements_versions.txt` before the first launch, it works fine.

**Comment by acheong08** [comment]
This could be the case. I'll snap it to `3.13.0` after some testing tomorrow.

**Comment by mathvafter** [comment]
> Hi, I don't know the details but this is only a problem with the newer version of gradio. When I downgrade it `3.13.0` by editing `requirements.txt` and `requirements_versions.txt` before the first launch, it works fine.

yep
downgrading gradio fix the issue

**Comment by acheong08** [comment]
Fixed https://github.com/acheong08/stable-diffusion-webui/commits/main
