### ISSUE TITLE
multipart consuming a byte

### ISSUE THREAD

**Issue by RayZ3R0** [acheong08/Diffusion-ColabUI#81]
I'm getting this error and the model isnt loading
```
WARNING:multipart.multipart:Consuming a byte in the end state
WARNING:multipart.multipart:Consuming a byte in the end state
```

**Comment by RayZ3R0** [comment]
Okay nevermind actually, the model shows its `loading...` but it still generates images

**Comment by acheong08** [comment]
@RayZ3R0 Can you please teach me how to fine tune a model?

**Comment by acheong08** [comment]
I have some training data and I would like to train it based on photos of myself
