### ISSUE TITLE
Cant load custom merged model

### ISSUE THREAD

**Issue by mathvafter** [acheong08/Diffusion-ColabUI#83]
![image](https://user-images.githubusercontent.com/122038692/212543815-2ef1b4ff-f6fc-4905-9bcb-eb652f6808a6.png)

merged model cant be loaded
always showing ^C and collab stopped running

**Comment by Vendetta-S** [comment]
I think, for some reason, it cannot load anything that is 7GB big no matter what you do.
Unless you somehow load a smaller model first and then load the big one.

**Comment by Vendetta-S** [comment]
Or, you merged a safetensors with a model that isn't a safetensors

**Comment by mathvafter** [comment]
nope, im not merging any safetensors model
issue occur recently, never had any issue before
i always merged custom model provided on the list

**Comment by acheong08** [comment]
7GB is the VRAM limit

**Comment by acheong08** [comment]
There is a checkbox for "large_models". It runs a workaround so you can run larger models but is very slow.

**Comment by hypergraphUniverse** [comment]
I have also encountered this problem with HD-20 model, I am wandering if is is practical to pay Colab probably get probably a better card with higher VRAM to solve this problem?

**Comment by acheong08** [comment]
> I am wondering if is is practical to pay Colab probably get a better card with higher VRAM to solve this problem?

I don't know anyone that pays for Colab

**Comment by mathvafter** [comment]
already use large_model
error still occured
