### ISSUE TITLE
Error merging checkpoints: device cuda is invalid

### ISSUE THREAD

**Issue by acheong08** [acheong08/Diffusion-ColabUI#86]
### Discussed in https://github.com/acheong08/Diffusion-ColabUI/discussions/85

<div type='discussions-op-text'>

<sup>Originally posted by **tranthai2k2** January 22, 2023</sup>
i try with safetensors and it gives error like this
![image](https://user-images.githubusercontent.com/97587560/213915752-2186b673-3352-47e1-97bb-fba69a44fa18.png)
![image](https://user-images.githubusercontent.com/97587560/213915815-42048bb2-1d47-4594-acfb-2415affe4f35.png)
![image](https://user-images.githubusercontent.com/97587560/213915862-6c8b3d58-4868-4528-9680-404dae8211df.png)
![Uploading image.png…]()

</div>

**Comment by Rorutop** [comment]
I did get error like that, but it's different
```Loading /content/stable-diffusion-webui/models/Stable-diffusion/AOM2-hard.safetensors...
Error loading/saving model file:
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/ui.py", line 1715, in modelmerger
    results = modules.extras.run_modelmerger(*args)
  File "/content/stable-diffusion-webui/modules/extras.py", line 169, in run_modelmerger
    theta_0 = sd_models.read_state_dict(primary_model_info.filename, map_location=devices.get_optimal_device())
NameError: name 'devices' is not defined```

any solution yet????

**Comment by acheong08** [comment]
Merging with safetensors still seems to be broken due to https://github.com/AUTOMATIC1111/stable-diffusion-webui

**Comment by Rorutop** [comment]
Another problem, a normal ckpt merge got me this error:
![image](https://user-images.githubusercontent.com/66291382/221779469-4e0538ce-d722-48ef-8146-53e0a40ef67b.png)
