### ISSUE TITLE
Results disappearing

### ISSUE THREAD

**Issue by Enferlain** [acheong08/Diffusion-ColabUI#87]
After the progress bar loads the generated picture disappears and it only shows 

![image](https://user-images.githubusercontent.com/15861396/214348470-25b5871d-d8be-4f35-8334-b19091e81b64.png)

Can't be downloaded even if I go on save below.

Any idea how to fix?

**Comment by Enferlain** [comment]
raceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/stable-diffusion-webui/modules/img2img.py", line 148, in img2img
    processed = process_images(p)
  File "/content/stable-diffusion-webui/modules/processing.py", line 476, in process_images
    res = process_images_inner(p)
  File "/content/stable-diffusion-webui/modules/processing.py", line 618, in process_images_inner
    devices.test_for_nans(x, "vae")
  File "/content/stable-diffusion-webui/modules/devices.py", line 136, in test_for_nans
    raise NansException(message)
modules.devices.NansException: A tensor with all NaNs was produced in VAE. This could be because there's not enough precision to represent the picture. Try adding --no-half-vae commandline argument to fix this.

**Comment by acheong08** [comment]
Use image history tab

**Comment by acheong08** [comment]
> modules.devices.NansException: A tensor with all NaNs was produced in VAE. This could be because there's not enough precision to represent the picture. Try adding --no-half-vae commandline argument to fix this.

Try disabling VAE.

**Comment by Enferlain** [comment]
Seems like it's gradio again. Thanks

**Comment by qwertea** [comment]
Use the commandline argument --gradio-queue to fix it.

**Comment by qwertea** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/6898

It's a temporary fix for the gradio probelm; the option will be on by default later on.
