### ISSUE TITLE
Broken optimizations

### ISSUE THREAD

**Issue by acheong08** [acheong08/Diffusion-ColabUI#9]
xformers and triton are both broken in Automatic1111's webui. I cannot fix this.

Can someone help?

**Comment by GrennKren** [comment]
Well.. I use xformers in kaggle and colab. Basically, installing in an inside virtual environment with Python 3.10

In Colab, you can choose between Pyenv and Conda for your virtual environment (download manually first).

In Kaggle , Conda was already built in.

<details>
<summary><b>Pyenv</b></summary>

```
#Download and installing
! curl https://pyenv.run | bash

#Initialization required environtment path
import os
os.environ['PYENV_ROOT']=f"{os.environ['HOME']}/.pyenv"
os.environ['PATH']+=f":{os.environ['PYENV_ROOT']}/bin"

#setup virtual environtment and Python 3.10
! sudo apt-get install -y libffi-dev
! pyenv install 3.10.7
! pyenv local 3.10.7
! python --version
! pyenv exec python --version

#Download Install xformers from my compiled binaries
!curl -L https://github.com/GrennKren/xformers_wheel/releases/download/v0.0.14_py310/xformers-0.0.14.dev0-cp310-cp310-linux_x86_64.whl --output "xformers-0.0.14.dev0-cp310-cp310-linux_x86_64.whl"
!pyenv exec pip install xformers-0.0.14.dev0-cp310-cp310-linux_x86_64.whl

#Launching webui
! COMMANDLINE_ARGS="--exit" REQS_FILE="requirements.txt" pyenv exec python launch.py
```
</details>

<details>
<summary><b>Conda</b></summary>

```
#Download and install IF conda wasnt installed
! curl --output conda.sh -L https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
! bash conda.sh -b    # -b for silent install

#Setup virtual environtment and python 3.10
! conda create -y -n YourEnvName python=3.10
! python --version
! conda run -n YourEnvName python --version

#Install Xformers 
! conda install -y -n p310 xformers -c xformers/label/dev

#Launching Webui
! COMMANDLINE_ARGS="--exit" REQS_FILE="requirements.txt" conda run -n p310 --no-capture-output python launch.py
# --no-capture-output is needed because conda run was not produce any output until the python program completed. 
```

</details>

In colab, I use pyenv and my compiled binaries. Why? No reason, it was just before I realized if xformers through Conda already had precompiled binaries. But pip still doesn't have it. Lol.

Yes, Kaggle I use Conda because it's much easier to setup.

**Comment by PreCoi** [comment]
用了ipynb文件，造成Colab账号封禁，提示如下：
由于存在疑似滥用行为，此帐号已被禁止访问 Colab 运行时。这不会影响对其他 Google 产品的访问。如果您认为这项决定有误，请查看[使用限制](https://research.google.com/colaboratory/faq.html#limitations-and-restrictions)并[提出申诉](https://colab.research.google.com/drive/16KHjxTu9I4r2uA9Px4BAiI5AL_GIi6LG#)。

**Comment by PreCoi** [comment]
用了ipynb文件后，造成Colab账号封禁，提示如下：
由于存在疑似滥用行为，此帐号已被禁止访问 Colab 运行时。这不会影响对其他 Google 产品的访问。如果您认为这项决定有误，请查看[使用限制](https://research.google.com/colaboratory/faq.html#limitations-and-restrictions)并[提出申诉](https://colab.research.google.com/drive/16KHjxTu9I4r2uA9Px4BAiI5AL_GIi6LG#)。

**Comment by PreCoi** [comment]
用了ipynb文件后，造成Colab账号封禁。

**Comment by GrennKren** [comment]
> 用了ipynb文件后，造成Colab账号封禁。

It may have something to do with that "model" . My two accounts, kaggle, were also recently locked. Right now I am trying again to make a new notebook without sharing the notebook in public.

**Comment by PreCoi** [comment]
> 
能解封吗？不知道能否申诉成功。

**Comment by acheong08** [comment]
Hello. I apologize that this has caused the lockdown of your accounts. It may have something to do with the violation of certain Google policies:
- creating deepfakes
- file hosting, media serving, or other web service offerings not related to interactive compute with Colab

This cannot be resolved by me.

**Comment by acheong08** [comment]
@PreCoi It might take a few days for your account to be unlocked. In the meantime, I recommend using dummy accounts for Colab. It is also not recommended to keep the colab running for more than two hours at a time.

**Comment by GrennKren** [comment]
Nah it's okay. I know somwthing likethis will happen. Probably you also
need to remove that from your public notebook.

**Comment by acheong08** [comment]
Triton has been fixed. Testing xformers

**Comment by acheong08** [comment]
Triton has not been fixed. Error: https://github.com/openai/triton/issues/625

**Comment by acheong08** [comment]
Upgrading to nightly triton

**Comment by acheong08** [comment]
More errors. Seems like default xformers is outdated. Installing newer xformers takes very long

**Comment by acheong08** [comment]
Xformers has no improvements considering the time it takes to update the dependencies
