### ISSUE TITLE
RuntimeError: Cannot add middleware after an application has started

### ISSUE THREAD

**Issue by GoAwayNow** [acheong08/Diffusion-ColabUI#90]
I'm not sure what's changed where, but as of either today or yesterday (I didn't try to use it yesterday), this error occurs right after the ui launches.

```
Traceback (most recent call last):
  File "launch.py", line 361, in <module>
    start()
  File "launch.py", line 356, in start
    webui.webui()
  File "/content/stable-diffusion-webui/webui.py", line 232, in webui
    app.add_middleware(GZipMiddleware, minimum_size=1000)
  File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 135, in add_middleware
    raise RuntimeError("Cannot add middleware after an application has started")
RuntimeError: Cannot add middleware after an application has started
```

**Comment by mae1221** [comment]
same thing happening to me. didnt do it at all yesterday and i have changed nothing between yesterday and today

**Comment by GoAwayNow** [comment]
Looks like it's an upstream issue coming from the UI, and beyond that from an update to fastapi. Doesn't belong here.

https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/7714
