### ISSUE TITLE
Add from google Drive

### ISSUE THREAD

**Issue by PutraCoud** [acheong08/Diffusion-ColabUI#93]
is it possible to add model from google drive link ?

**Comment by acheong08** [comment]
Yup! Just paste in your google drive link in the same place and it automatically detects it as google drive

**Comment by acheong08** [comment]
Must be of format: https://drive.google.com/...

**Comment by IchLiebeDich-Guet** [comment]
> URL must start with `https://drive.google.com`

Can give me an example? I dont know how to get URL from a model which in my Google drive.
