### ISSUE TITLE
Generated Image not Showing

### ISSUE THREAD

**Issue by Tsuki321** [acheong08/Diffusion-ColabUI#94]
Been having this problem for a few days whenever I try to generate an image, after it is done it doesn't show the image.
![Screenshot_2023-02-21-10-02-38-29](https://user-images.githubusercontent.com/103306466/220229226-bcf30737-e02b-41b0-a5e1-91bb64d926d0.jpg)

**Comment by acheong08** [comment]
idk if mobile works properly. also, are you using the new UI or the old one?

**Comment by Tsuki321** [comment]
The new one.

**Comment by acheong08** [comment]
Try using the older version by unticking the new ui checkbox

**Comment by Vendetta-S** [comment]
I think, if you can, use the Gdrive option. The image will be saved there so you won't lose anything.

**Comment by Tsuki321** [comment]
It working now just had to switch back to the old UI
