### ISSUE TITLE
How to use safetensors?

### ISSUE THREAD

**Issue by IchLiebeDich-Guet** [acheong08/Diffusion-ColabUI#96]
By read your code, I find that it supported safetensors, but I can't use it.

My model in Google drive and add the URL to here:
![F2)ASUI(8NCKZTEH{7717SE](https://user-images.githubusercontent.com/97378825/220829202-7794ff84-0385-40bd-9d5a-cd2fa4a5ce0b.png)

But when downloading, it is ckpt:
![_@28M F~4 722 T@7`WRR9A](https://user-images.githubusercontent.com/97378825/220829417-d685e616-af48-405f-ab58-050985884beb.png)

And it gets error:
![9JL_ E{(1SVFGOEEUU)RG@A](https://user-images.githubusercontent.com/97378825/220829635-cb368476-ef39-4878-bbcd-cb73cbec719b.png)

My model URL: https://drive.google.com/file/d/1wpL7zyzBE6BZegHNguc0WO91uGXbwLTK/view?usp=share_link

What should I do to use safetensors?

**Comment by acheong08** [comment]
That is a flaw in the design. You'll have to manually rename it from the sidebar if it comes from Google Drive, clear the model list, and run the WebUI again.

**Comment by IchLiebeDich-Guet** [comment]
> That is a flaw in the design. You'll have to manually rename it from the sidebar if it comes from Google Drive, clear the model list, and run the WebUI again.

Oh，it can run! But not success.


I rename chilloutmix_NiPrunedFp32Fix.sofetensors.ckpt to chilloutmix_NiPrunedFp32Fix.sofetensors, then clear model list, and start webui again, it look like ok.
![正常运行](https://user-images.githubusercontent.com/97378825/220857238-27c27faa-e5cf-471c-a3e2-23a27fc63b0d.png)


But after click the link, the UI get wrong, like this:
![界面异常](https://user-images.githubusercontent.com/97378825/220857331-8ed6977c-2549-472b-a345-1fe16b6fae59.png)


This is a part of wrongs:
![报错信息](https://user-images.githubusercontent.com/97378825/220857498-8409b149-09b7-414e-8e87-ca825f5025e9.png)

**Comment by acheong08** [comment]
or maybe swap back to the old UI by unticking the checkbox in Colab

**Comment by IchLiebeDich-Guet** [comment]
> That is a flaw in the design. You'll have to manually rename it from the sidebar if it comes from Google Drive, clear the model list, and run the WebUI again.

I try it again and it's OK. Thank.
But I dont know why. I only chance the modelname, when rename , is chilloutmix_NiPrunedFp32Fix.ckpt to chilloutmix_NiPrunedFp32Fix.sofetensors, 
not chilloutmix_NiPrunedFp32Fix.sofetensors.ckpt to chilloutmix_NiPrunedFp32Fix.sofetensors,

![最后](https://user-images.githubusercontent.com/97378825/220870464-c4ba6792-764c-4908-aae0-c040eeaaabad.png)

**Comment by IchLiebeDich-Guet** [comment]
> There was error with the v2. Maybe try running again. I just updated my fork.

nice, I will try the newone

**Comment by IchLiebeDich-Guet** [comment]
> or maybe swap back to the old UI by unticking the checkbox in Colab

ok, I found thiw checkbox, I have ever think that the new UI is the UI get wrong, it have too many black block, hahaha
