### ISSUE TITLE
New webui looks weird a

### ISSUE THREAD

**Issue by yokesh-r** [acheong08/Diffusion-ColabUI#98]
The new webui looks weird and unable to type prompts there, is there a way to restore to previous gradio ui
![Screenshot 2023-02-26 085448](https://user-images.githubusercontent.com/67429601/221390674-0044b6cc-c9f2-4d49-b3f3-abcb3119a823.png)

**Comment by acheong08** [comment]
There is a checkbox in the Colab

**Comment by yokesh-r** [comment]
Can you point me where I have to click the check box ?

**Comment by acheong08** [comment]
![image](https://user-images.githubusercontent.com/36258159/221392372-053a1bbc-7f4c-45ef-b81e-1406d96cd6a4.png)

**Comment by acheong08** [comment]
I also just updated the new_ui to fix a few bugs
