### ISSUE TITLE
There's no save everything locally to GDrive like before?

### ISSUE THREAD

**Issue by tmatzxzone** [acheong08/Diffusion-ColabUI#99]
Why you dont make save everything on drive like u used to have before? so we dont need to redownload everything back every single launch.
Is there a problem with that?
If there's isnt a problem can you put it back? thx

**Comment by acheong08** [comment]
https://colab.research.google.com/github/acheong08/Diffusion-ColabUI/blob/main/Diffusion_WebUI.ipynb
